modules:
  TKMath:
    enabled: true
    config: TKMath.yaml
  TKBRep:
    enabled: true
    config: TKBRep.yaml
  TKTopAlgo:
    enabled: true
    config: TKTopAlgo.yaml
  TKGeomBase:
    enabled: true
    config: TKGeomBase.yaml
