module: TKBRep

classes:
  TopoDS_Shape:
    constructors: []
    methods:
      Orientation:
        overloads:
          - match: []
            suffix: _Get
          - match: [TopAbs_Orientation]
            suffix: _Set
      Free:
        overloads:
          - match: []
            suffix: _Get
          - match: [Standard_Boolean]
            suffix: _Set
      Modified:
        overloads:
          - match: []
            suffix: _Get
          - match: [Standard_Boolean]
            suffix: _Set
      Checked:
        overloads:
          - match: []
            suffix: _Get
          - match: [Standard_Boolean]
            suffix: _Set
      Orientable:
        overloads:
          - match: []
            suffix: _Get
          - match: [Standard_Boolean]
            suffix: _Set
      Closed:
        overloads:
          - match: []
            suffix: _Get
          - match: [Standard_Boolean]
            suffix: _Set
      Infinite:
        overloads:
          - match: []
            suffix: _Get
          - match: [Standard_Boolean]
            suffix: _Set
      Convex:
        overloads:
          - match: []
            suffix: _Get
          - match: [Standard_Boolean]
            suffix: _Set
      Locked:
        overloads:
          - match: []
            suffix: _Get
          - match: [Standard_Boolean]
            suffix: _Set
    skip: []

  TopoDS_Vertex:
    constructors: []

  TopoDS_Edge:
    constructors: []

  TopoDS_Wire:
    constructors: []

  TopoDS_Face:
    constructors: []

  TopoDS_Shell:
    constructors: []

  TopoDS_Solid:
    constructors: []

  TopoDS_Compound:
    constructors: []

  TopoDS_Builder:
    constructors:
      - match: []
    methods:
      MakeWire:
        output_args: true
      MakeShell:
        output_args: true
      MakeSolid:
        output_args: true
      MakeCompound:
        output_args: true
      Add:
        mut_args: [S]
      Remove:
        mut_args: [S]
    skip: [MakeCompSolid]

  TopoDS_Iterator:
    constructors: []

  TopExp_Explorer:
    constructors: []

  BRep_Builder:
    constructors:
      - match: []
    methods:
      MakeVertex:
        overloads:
          - match: [TopoDS_Vertex]
            suffix: _Empty
            output_args: true
          - match: [TopoDS_Vertex, gp_Pnt, Standard_Real]
            suffix: _WithPnt
            output_args: true
      MakeEdge:
        output_args: true
      MakeFace:
        output_args: true
      MakeWire:
        output_args: true
      MakeShell:
        output_args: true
      MakeSolid:
        output_args: true
      MakeCompound:
        output_args: true
      Add:
        mut_args: [S]
      Remove:
        mut_args: [S]
      UpdateVertex:
        overloads:
          - match: [TopoDS_Vertex, Standard_Real]
            suffix: _Tol
          - match: [TopoDS_Vertex, gp_Pnt, Standard_Real]
            suffix: _PntTol
    skip: [Continuity, Range, Transfert, UpdateEdge, UpdateFace]

  BRep_Tool:
    constructors: []
    methods:
      Tolerance:
        overloads:
          - match: [TopoDS_Face]
            suffix: _Face
          - match: [TopoDS_Edge]
            suffix: _Edge
          - match: [TopoDS_Vertex]
            suffix: _Vertex
      IsGeometric:
        overloads:
          - match: [TopoDS_Edge]
            suffix: _Edge
          - match: [TopoDS_Face]
            suffix: _Face
      IsClosed:
        overloads:
          - match: [TopoDS_Shape]
            suffix: _Shape
    skip: [Continuity, HasContinuity, MaxContinuity, NaturalRestriction, SetUVPoints, UVPoints, Triangulations, Range, Parameter, Parameters]

enums:
  TopAbs_ShapeEnum:
    include: TopAbs_ShapeEnum.hxx
  TopAbs_Orientation:
    include: TopAbs_Orientation.hxx
  TopAbs_State:
    include: TopAbs_State.hxx
