module: TKMath

classes:
  gp_XYZ:
    constructors: []
    methods:
      SetCoord:
        overloads:
          - match: [Standard_Integer, Standard_Real]
            suffix: _Index
          - match: [Standard_Real, Standard_Real, Standard_Real]
            suffix: _XYZ
      Coord:
        overloads:
          - match: [Standard_Integer]
            suffix: _Index
      Multiply:
        overloads:
          - match: [Standard_Real]
            suffix: _Scalar
          - match: [gp_XYZ]
            suffix: _XYZ
          - match: [gp_Mat]
            suffix: _Mat
      Multiplied:
        overloads:
          - match: [Standard_Real]
            suffix: _Scalar
          - match: [gp_XYZ]
            suffix: _XYZ
          - match: [gp_Mat]
            suffix: _Mat
    skip: [SetLinearForm]

  gp_Pnt:
    constructors: []
    methods:
      SetCoord:
        overloads:
          - match: [Standard_Integer, Standard_Real]
            suffix: _Index
          - match: [Standard_Real, Standard_Real, Standard_Real]
            suffix: _XYZ
      Coord:
        overloads:
          - match: [Standard_Integer]
            suffix: _Index
      Mirror:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Mirrored:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Translate:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt
      Translated:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt

  gp_Vec:
    constructors:
      - match: [gp_Dir]
        factory: FromDir
      - match: [gp_XYZ]
        factory: FromXYZ
    methods:
      SetCoord:
        overloads:
          - match: [Standard_Integer, Standard_Real]
            suffix: _Index
          - match: [Standard_Real, Standard_Real, Standard_Real]
            suffix: _XYZ
      Coord:
        overloads:
          - match: [Standard_Integer]
            suffix: _Index
      Mirror:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Mirrored:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
    skip: [SetLinearForm]

  gp_Dir:
    constructors:
      - match: [gp_Vec]
        factory: FromVec
      - match: [gp_XYZ]
        factory: FromXYZ
    methods:
      SetCoord:
        overloads:
          - match: [Standard_Integer, Standard_Real]
            suffix: _Index
          - match: [Standard_Real, Standard_Real, Standard_Real]
            suffix: _XYZ
      Coord:
        overloads:
          - match: [Standard_Integer]
            suffix: _Index
      Mirror:
        overloads:
          - match: [gp_Dir]
            suffix: _Dir
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Mirrored:
        overloads:
          - match: [gp_Dir]
            suffix: _Dir
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2

  gp_Ax1:
    constructors: []
    methods:
      Mirror:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Mirrored:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Translate:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt
      Translated:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt

  gp_Ax2:
    constructors: []
    methods:
      IsCoplanar:
        overloads:
          - match: [gp_Ax2, Standard_Real, Standard_Real]
            suffix: _Ax2
          - match: [gp_Ax1, Standard_Real, Standard_Real]
            suffix: _Ax1
      Mirror:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Mirrored:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Translate:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt
      Translated:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt

  gp_Ax3:
    constructors: []
    methods:
      IsCoplanar:
        overloads:
          - match: [gp_Ax3, Standard_Real, Standard_Real]
            suffix: _Ax3
          - match: [gp_Ax1, Standard_Real, Standard_Real]
            suffix: _Ax1
      Mirror:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Mirrored:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Translate:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt
      Translated:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt

  gp_Trsf:
    constructors: []
    methods:
      SetMirror:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      SetRotation:
        overloads:
          - match: [gp_Ax1, Standard_Real]
            suffix: _Ax1
          - match: [gp_Quaternion]
            suffix: _Quat
      SetTransformation:
        overloads:
          - match: [gp_Ax3]
            suffix: _Ax3
          - match: [gp_Ax3, gp_Ax3]
            suffix: _Ax3Ax3
      SetTranslation:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt
      GetRotation:
        overloads:
          - match: []
            suffix: _Quat
    skip: [SetValues, Transforms]

  gp_Mat:
    constructors: []
    methods:
      Multiply:
        overloads:
          - match: [Standard_Real]
            suffix: _Scalar
          - match: [gp_Mat]
            suffix: _Mat
      Multiplied:
        overloads:
          - match: [Standard_Real]
            suffix: _Scalar
          - match: [gp_Mat]
            suffix: _Mat
    skip: [ChangeValue]

  gp_Quaternion:
    constructors:
      - match: [gp_Vec, gp_Vec]
        factory: FromVecs
    methods:
      SetRotation:
        overloads:
          - match: [gp_Vec, gp_Vec]
            suffix: _VecVec
          - match: [gp_Vec, gp_Vec, gp_Vec]
            suffix: _VecVecVec
      Set:
        overloads:
          - match: [Standard_Real, Standard_Real, Standard_Real, Standard_Real]
            suffix: _XYZW
      Multiply:
        overloads:
          - match: [gp_Quaternion]
            suffix: _Quat
          - match: [gp_Vec]
            suffix: _Vec
    skip: [GetVectorAndAngle, GetEulerAngles]

  gp_Lin:
    constructors: []
    methods:
      Distance:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Lin]
            suffix: _Lin
      SquareDistance:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Lin]
            suffix: _Lin
      Mirror:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Mirrored:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Translate:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt
      Translated:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt

  gp_Pln:
    constructors: []
    methods:
      Distance:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Lin]
            suffix: _Lin
          - match: [gp_Pln]
            suffix: _Pln
      SquareDistance:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Lin]
            suffix: _Lin
          - match: [gp_Pln]
            suffix: _Pln
      Contains:
        overloads:
          - match: [gp_Pnt, Standard_Real]
            suffix: _Pnt
          - match: [gp_Lin, Standard_Real, Standard_Real]
            suffix: _Lin
      Mirror:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Mirrored:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Translate:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt
      Translated:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt
    skip: [Coefficients]

  gp_Circ:
    constructors: []
    methods:
      Mirror:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Mirrored:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Translate:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt
      Translated:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt

  gp_Elips:
    constructors: []
    methods:
      Mirror:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Mirrored:
        overloads:
          - match: [gp_Pnt]
            suffix: _Pnt
          - match: [gp_Ax1]
            suffix: _Ax1
          - match: [gp_Ax2]
            suffix: _Ax2
      Translate:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt
      Translated:
        overloads:
          - match: [gp_Vec]
            suffix: _Vec
          - match: [gp_Pnt, gp_Pnt]
            suffix: _PntPnt

  gp_XY:
    constructors: []
    methods:
      SetCoord:
        overloads:
          - match: [Standard_Integer, Standard_Real]
            suffix: _Index
          - match: [Standard_Real, Standard_Real]
            suffix: _XY
      Coord:
        overloads:
          - match: [Standard_Integer]
            suffix: _Index
      Multiply:
        overloads:
          - match: [Standard_Real]
            suffix: _Scalar
          - match: [gp_XY]
            suffix: _XY
      Multiplied:
        overloads:
          - match: [Standard_Real]
            suffix: _Scalar
          - match: [gp_XY]
            suffix: _XY
    skip: [SetLinearForm, ChangeCoord]

  gp_Pnt2d:
    constructors: []
    methods:
      SetCoord:
        overloads:
          - match: [Standard_Integer, Standard_Real]
            suffix: _Index
          - match: [Standard_Real, Standard_Real]
            suffix: _XY
      Coord:
        overloads:
          - match: [Standard_Integer]
            suffix: _Index
      Mirror:
        overloads:
          - match: [gp_Pnt2d]
            suffix: _Pnt
          - match: [gp_Ax2d]
            suffix: _Ax
      Mirrored:
        overloads:
          - match: [gp_Pnt2d]
            suffix: _Pnt
          - match: [gp_Ax2d]
            suffix: _Ax
      Translate:
        overloads:
          - match: [gp_Vec2d]
            suffix: _Vec
          - match: [gp_Pnt2d, gp_Pnt2d]
            suffix: _PntPnt
      Translated:
        overloads:
          - match: [gp_Vec2d]
            suffix: _Vec
          - match: [gp_Pnt2d, gp_Pnt2d]
            suffix: _PntPnt
    skip: [ChangeCoord]

  gp_Vec2d:
    constructors:
      - match: [gp_Dir2d]
        factory: FromDir
      - match: [gp_XY]
        factory: FromXY
    methods:
      SetCoord:
        overloads:
          - match: [Standard_Integer, Standard_Real]
            suffix: _Index
          - match: [Standard_Real, Standard_Real]
            suffix: _XY
      Coord:
        overloads:
          - match: [Standard_Integer]
            suffix: _Index
      Mirror:
        overloads:
          - match: [gp_Vec2d]
            suffix: _Vec
          - match: [gp_Ax2d]
            suffix: _Ax
      Mirrored:
        overloads:
          - match: [gp_Vec2d]
            suffix: _Vec
          - match: [gp_Ax2d]
            suffix: _Ax
    skip: [SetLinearForm]

  gp_Dir2d:
    constructors:
      - match: [gp_Vec2d]
        factory: FromVec
      - match: [gp_XY]
        factory: FromXY
    methods:
      SetCoord:
        overloads:
          - match: [Standard_Integer, Standard_Real]
            suffix: _Index
          - match: [Standard_Real, Standard_Real]
            suffix: _XY
      Coord:
        overloads:
          - match: [Standard_Integer]
            suffix: _Index
      Mirror:
        overloads:
          - match: [gp_Dir2d]
            suffix: _Dir
          - match: [gp_Ax2d]
            suffix: _Ax
      Mirrored:
        overloads:
          - match: [gp_Dir2d]
            suffix: _Dir
          - match: [gp_Ax2d]
            suffix: _Ax

  gp_Ax2d:
    constructors: []
    methods:
      Mirror:
        overloads:
          - match: [gp_Pnt2d]
            suffix: _Pnt
          - match: [gp_Ax2d]
            suffix: _Ax
      Mirrored:
        overloads:
          - match: [gp_Pnt2d]
            suffix: _Pnt
          - match: [gp_Ax2d]
            suffix: _Ax
      Translate:
        overloads:
          - match: [gp_Vec2d]
            suffix: _Vec
          - match: [gp_Pnt2d, gp_Pnt2d]
            suffix: _PntPnt
      Translated:
        overloads:
          - match: [gp_Vec2d]
            suffix: _Vec
          - match: [gp_Pnt2d, gp_Pnt2d]
            suffix: _PntPnt

  gp_Ax22d:
    constructors:
      - match: [gp_Pnt2d, gp_Dir2d, gp_Dir2d]
        factory: FromPntDirDir
      - match: [gp_Pnt2d, gp_Dir2d, Standard_Boolean]
        factory: FromPntDir
    methods:
      Mirror:
        overloads:
          - match: [gp_Pnt2d]
            suffix: _Pnt
          - match: [gp_Ax2d]
            suffix: _Ax
      Mirrored:
        overloads:
          - match: [gp_Pnt2d]
            suffix: _Pnt
          - match: [gp_Ax2d]
            suffix: _Ax
      Translate:
        overloads:
          - match: [gp_Vec2d]
            suffix: _Vec
          - match: [gp_Pnt2d, gp_Pnt2d]
            suffix: _PntPnt
      Translated:
        overloads:
          - match: [gp_Vec2d]
            suffix: _Vec
          - match: [gp_Pnt2d, gp_Pnt2d]
            suffix: _PntPnt

  gp_Lin2d:
    constructors: []
    methods:
      Distance:
        overloads:
          - match: [gp_Pnt2d]
            suffix: _Pnt
          - match: [gp_Lin2d]
            suffix: _Lin
      SquareDistance:
        overloads:
          - match: [gp_Pnt2d]
            suffix: _Pnt
          - match: [gp_Lin2d]
            suffix: _Lin
      Mirror:
        overloads:
          - match: [gp_Pnt2d]
            suffix: _Pnt
          - match: [gp_Ax2d]
            suffix: _Ax
      Mirrored:
        overloads:
          - match: [gp_Pnt2d]
            suffix: _Pnt
          - match: [gp_Ax2d]
            suffix: _Ax
      Translate:
        overloads:
          - match: [gp_Vec2d]
            suffix: _Vec
          - match: [gp_Pnt2d, gp_Pnt2d]
            suffix: _PntPnt
      Translated:
        overloads:
          - match: [gp_Vec2d]
            suffix: _Vec
          - match: [gp_Pnt2d, gp_Pnt2d]
            suffix: _PntPnt
    skip: [Coefficients]

  gp_Circ2d:
    constructors:
      - match: [gp_Ax22d, Standard_Real]
        factory: FromAx22d
    methods:
      Mirror:
        overloads:
          - match: [gp_Pnt2d]
            suffix: _Pnt
          - match: [gp_Ax2d]
            suffix: _Ax
      Mirrored:
        overloads:
          - match: [gp_Pnt2d]
            suffix: _Pnt
          - match: [gp_Ax2d]
            suffix: _Ax
      Translate:
        overloads:
          - match: [gp_Vec2d]
            suffix: _Vec
          - match: [gp_Pnt2d, gp_Pnt2d]
            suffix: _PntPnt
      Translated:
        overloads:
          - match: [gp_Vec2d]
            suffix: _Vec
          - match: [gp_Pnt2d, gp_Pnt2d]
            suffix: _PntPnt
    skip: [Coefficients]

enums:
  gp_TrsfForm:
    include: gp_TrsfForm.hxx
  gp_EulerSequence:
    include: gp_EulerSequence.hxx
